-- 코드를 입력하세요
SELECT ROUND(AVG(DAILY_FEE)) AS AVERAGE_FEE FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV';

# SELECT CAR_TYPE, SUM(DAILY_FEE) AS SUM_FEE FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = 'SUV';